Travis config
BDT-02/pivotal-api-g1 pull request #3
Opened 2019-01-07 13:22 UTC by acamacho82

2019-01-08 19:19 UTC, sperBruno commented
Make tests to pass on travis

2019-01-08 20:00 UTC, acamacho82 commented
Done, the unittest is for project creation was added

2019-01-08 21:57 UTC, sperBruno requested changes
Use behave command to run the feature files inside the .travis.yml file

2019-01-09 05:07 UTC, acamacho82 commented
Done!!

2019-01-09 12:31 UTC, sperBruno approved these changes

2019-01-09 12:37 UTC, merged